interface Decrementor {
  constructor(Incrementor incrementor);
  unsigned long decrement();
};

dictionary Properties {
  DOMString name;
  unsigned long count;
};

interface Incrementor {
  constructor();
  constructor(unsigned long initial);
  constructor(DOMString initial);
  unsigned long increment();
  Decrementor getDecrementor();
  [SameObject] readonly attribute Properties props;
  attribute Properties settableProps;
};
